image: riha-test-env

stages:
    - test
    - build

test:
    stage: test
    script:
        - mvn clean test
    tags:
        - riha

build:
    stage: build
    script:
        - mvn clean package
    artifacts:
        paths:
            - target/*.jar
    tags:
        - riha